
version: '2.3'
services:
  kindlytree_ai:
    #image: pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-devel
    build: ./
    container_name: kindlytree_ai
    runtime: nvidia
    image: kindlytree_ai/pytorch:1.0
    ports:
      - "8081:8081"
      - "1234:1234"    
    environment:
      - DISPLAY=unix$DISPLAY
      - GDK_SCALE
      - GDK_DPI_SCALE
    volumes:
      - ../../../:/home/kindlytree
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: "tail -f /dev/null"
    #command: bash -c "./home/kindlytree/docker/dl/pytorch/jupyter_notebook.sh && tail -f /dev/null"